"""Initial

Revision ID: 38424f3143e4
Revises: 
Create Date: 2022-06-16 19:01:02.180637

"""
from alembic import op
from sqlalchemy import Column, Enum
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '38424f3143e4'
down_revision = None
branch_labels = None
depends_on = None

UnitType = Enum('offer', 'category', name='type')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
                    sa.Column('import_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('import_id', name=op.f('pk__imports'))
                    )
    op.create_table('units',
                    sa.Column('import_id', sa.Integer(), nullable=False),
                    sa.Column('unit_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('type', UnitType, nullable=False),
                    sa.ForeignKeyConstraint(['import_id'], ['imports.import_id'],
                                            name=op.f('fk__units__import_id__imports')),
                    sa.PrimaryKeyConstraint('import_id', 'unit_id', name=op.f('pk__units'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    op.drop_table('imports')
    UnitType.drop(op.get_bind())
    # ### end Alembic commands ###
